project_id = "hdizvbyvtlmkwprhdnzr"

[functions.receive-order]
verify_jwt = false

[functions.edit-order]
verify_jwt = false

[functions.delete-order]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false